config/routes.rb
TestApp::Application.routes.draw do
  resources :medicines
  match 'medicines/placed_order/:id' => 'medicines#placed_order',:as => "placed_order"

  devise_for :users

  

   root :to => 'medicines#index'

end

app/models/medicine.rb
class Medicine < ActiveRecord::Base
  attr_accessible :code_for_placing_order, :name, :ordered_qty
  validates :code_for_placing_order, :presence =>true
  validates :name,:presence =>true
  validates :ordered_qty,:presence =>true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable, :mailchimp

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:user_name,:join_mailing_list
  validates :user_name, :presence => true, :uniqueness => true
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  # GET /medicines
  # GET /medicines.json
  def index
    @medicines = Medicine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @medicines }
    end
  end

  # GET /medicines/1
  # GET /medicines/1.json
  def show
    @medicine = Medicine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @medicine }
    end
  end

  # GET /medicines/new
  # GET /medicines/new.json
  def new
    @medicine = Medicine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @medicine }
    end
  end

  # GET /medicines/1/edit
  def edit
    @medicine = Medicine.find(params[:id])
  end

  # POST /medicines
  # POST /medicines.json
  def create
    @medicine = Medicine.new(params[:medicine])

    respond_to do |format|
      if @medicine.save
        format.html { redirect_to @medicine, notice: 'Medicine was successfully created.' }
        format.json { render json: @medicine, status: :created, location: @medicine }
      else
        format.html { render action: "new" }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /medicines/1
  # PUT /medicines/1.json
  def update
    @medicine = Medicine.find(params[:id])

    respond_to do |format|
      if @medicine.update_attributes(params[:medicine])
        format.html { redirect_to @medicine, notice: 'Medicine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicines/1
  # DELETE /medicines/1.json
  def destroy
    @medicine = Medicine.find(params[:id])
    @medicine.destroy

    respond_to do |format|
      format.html { redirect_to medicines_url }
      format.json { head :no_content }
    end
  end
  def placed_order
  	@medicine = Medicine.find(params[:id])
  	#render :text => "#{yield(@medicine.code_for_placing_order)}"
#	render :update do |page|
#  		page.replace_html 'placed', :text => "<%= yield(@medicine.code_for_placing_order) %>"
#	end
	respond_to do |format|
      format.html 
      format.js 
    end	
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<body>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
  <div class="navbar navbar-fixed-top">
    <div class='navbar-inner'>
      <div class='container'>
        <a class='btn btn-navbar' data-toggle='collapse' data-target='.nav-collapse'
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
        </a>
        <a class='brand' href='/'>Test app</a>
        <% if user_signed_in? %>
        			<div style='float:right;margin-top:9px;margin-right:18px;'>Logged in with <b><%= current_user.user_name%></b>&nbsp&nbsp&nbsp&nbsp 
          		<%= link_to "Sign Out",destroy_user_session_path, :style => "float:right;", :method => :delete %></div>
          <% else %>
          		<%= link_to "Log In",new_user_session_path, :style => "float:right;margin-top:9px;"%>
          		<%= link_to "Sign Up",new_user_registration_path, :style => "float:right;margin-top:9px;margin-right:18px;" %>          		
        <% end %>      

      </div>
      <div class='message'>
       <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == :notice ? 'sucess' : 'error' %>">
        <a class='close' data-dismiss='alert'>x</a>
        <%= msg%>
       <% end %>
     </div>
  </div>
  <div class="container">
  <div class="row">
    <%= yield %>
    </div>
  </div>
  <div class="navbar navbar-fixed-bottom">
    <div class='navbar-inner'>
      <div class='container'>
        <a class='btn btn-navbar' data-toggle='collapse' data-target='.nav-collapse'
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
        </a>
        <div class="muted credit">© Company 2013</div>
    </div>
  </div>
</body>
</html>

app/views/medicines/_form.html.erb
<%if current_user.is_admin? == true %>
<%= form_for @medicine, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :code_for_placing_order, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :code_for_placing_order, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ordered_qty, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :ordered_qty, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                medicines_path, :class => 'btn btn-danger' %>
  </div>
<% end %>
<%end%>

app/views/medicines/edit.html.erb
<%- model_class = Medicine -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/medicines/index.html.erb
<%- model_class = Medicine -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<%if  @medicines.count == 0 %>
<h2 style="color:lightblue; margin-left:30px;">No Medicine Record </h2>
<%else%>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:code_for_placing_order) %></th>
      <th><%= model_class.human_attribute_name(:ordered_qty) %></th>
        <% if user_signed_in? %>
      <%if current_user.is_admin? == false %>
      	<th><%=t 'order'%></th>
      <%else%>
         <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
      <%end%>
    </tr>
  </thead>
  <tbody>
    <% @medicines.each do |medicine| %>
      <tr>
        <td><%= link_to medicine.id, medicine_path(medicine) %></td>
        <td><%= medicine.name %></td>
        <td><%= medicine.code_for_placing_order %></td>
        <td><%= medicine.ordered_qty %></td>
        <td>
          <% if user_signed_in? %>
      	<%if current_user.is_admin? == false %>
      	  <%= link_to 'Order',placed_order_path(medicine), :class => 'btn btn-mini btn-primary' , :remote=> true%>

      	<%else%>        
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_medicine_path(medicine), :class => 'btn btn-mini btn-primary' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      medicine_path(medicine),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
			<%end%>
			<%end%>                      
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%end%>
<div class="placed">

</div>
  <% if user_signed_in? %>
<%if current_user.is_admin? == true %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_medicine_path,
            :class => 'btn btn-primary' %>
<% end %>
<%end%>

app/views/medicines/new.html.erb
<%- model_class = Medicine -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/medicines/placed_order.js.erb
$('.placed').html(" <div class='message'><div class='alert alert-sucess'><b>Code for placing order: </b> <%= escape_javascript(render :text => "#{@medicine.code_for_placing_order}") %><a class='close' data-dismiss='alert'>x</a></div></div>")

app/views/medicines/show.html.erb
<%- model_class = Medicine -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @medicine.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:code_for_placing_order) %>:</strong></dt>
  <dd><%= @medicine.code_for_placing_order %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ordered_qty) %>:</strong></dt>
  <dd><%= @medicine.ordered_qty %></dd>
</dl>
<%if current_user.is_admin? == true %>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              medicines_path, :class => 'btn btn-primary'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_medicine_path(@medicine), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              medicine_path(@medicine),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
<%end%>